### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-intro#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://glacial-plains-8264.herokuapp.com) and meets the following [project](http://lansingcodelab.com/lessons/rails-intro/1) criteria:
- [x] a `home` action in a `StaticController` is served to `/`, which shows some content unique to this page
- [x] an `about` action in a `StaticController` is served to `/about`, which shows some content unique to this page
- [x] a `cats` action in a `StaticController` is served to `/cat-pictures`, which shows at least 1 cat picture, then shows the number of cat pictures requested when visiting `/cat-pictures/3` (for 3 cats) or `/cat-pictures/5` (for 5 cats), for example
- [x] well-labeled links to all of the above routes exist on all pages of the app, using path helpers and without including the same code in every view file
- [x] there's some CSS that goes through Rails' asset pipeline that visibly affects every page
- [x] at least 1 helper method is used for some visible effect on at least 1 page

**Comment by chrisvfritz** [comment]
:+1: :shipit:
